# Generated by Django 5.2.14 on 2026-06-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='symptoms.assessment'),
        ),
    ]
