# Generated by Django 5.2.14 on 2026-06-09 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('appointment_upcoming', 'Appointment Upcoming'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_completed', 'Appointment Completed'), ('suggestion_posted', 'New Doctor Suggestion'), ('medication_added', 'Medication Added'), ('medication_updated', 'Medication Updated'), ('general', 'General')], default='general', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('navigate_to', models.CharField(blank=True, help_text='Frontend route e.g. /appointments', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
