# Generated by Django 5.2.14 on 2026-06-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of related object e.g. suggestion_id', null=True),
        ),
    ]
