# Generated by Django 5.2.14 on 2026-05-31 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_medication_user'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsuggestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed suggestion or new findings'),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='disease_name',
            field=models.CharField(blank=True, help_text='Related disease if any', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_suggestions/documents/'),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='document_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='is_new_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible to all doctors'),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('recommendation', 'Patient Recommendation'), ('research', 'Medical Research / New Finding'), ('case_study', 'Case Study'), ('general', 'General Advisory')], default='recommendation', max_length=30),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doctorsuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctorsuggestion',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_suggestions', to='recommendations.recommendation'),
        ),
    ]
