# Generated by Django 5.2.14 on 2026-05-31 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_doctorsuggestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsuggestion',
            name='specialization',
        ),
    ]
