# Generated by Django 5.2.14 on 2026-05-21 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField()),
                ('severity', models.PositiveIntegerField(default=3)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('predictions', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('matched_symptoms', models.JSONField(blank=True, null=True)),
                ('unknown_symptoms', models.JSONField(blank=True, null=True)),
                ('total_severity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sympotoms_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
