# Generated by Django 5.2.14 on 2026-05-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
    ]
