# Generated by Django 5.2.14 on 2026-05-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_doctor_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('BDS', 'BDS'), ('MDS', 'MDS'), ('DM', 'DM'), ('MCh', 'MCh'), ('BHMS', 'BHMS'), ('BAMS', 'BAMS'), ('BUMS', 'BUMS'), ('DNB', 'DNB')], default='MBBS', max_length=50),
            preserve_default=False,
        ),
    ]
