# Generated by Django 5.2.14 on 2026-05-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={},
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='history_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('family', 'Family')], default='patient', max_length=10),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='parent_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
