# Generated by Django 5.2.14 on 2026-05-31 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_medicalhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
    ]
