# Generated by Django 5.2.14 on 2026-05-31 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_medication_notes_medication_prescribed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='user',
            field=models.ForeignKey(help_text='The patient who takes this medication', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
    ]
