name: Build and deploy Python app to Azure Web App - healthcare-backend-khushbu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and Start virtual environment and Install dependencies
        run: |
          cd healthcare_symptom_analysis
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            healthcare_symptom_analysis/
            !healthcare_symptom_analysis/antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_94A16CB5274F45799C2320B3A6C0B828 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02309D066E0F4699815AAB94141B88EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C71AB380CA9E46CB908F07A0A1AEFEF0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'healthcare-backend-khushbu'
          slot-name: 'Production'
